### ISSUE TITLE
Remove `/huc8` fragment from `boundary` endpoint

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#107]
Right now a valid endpoint for a HUC8 boundary looks like this:

https://earthmaps.io/boundary/huc/huc8/19070506

Since those HUC IDs are unique, it'd make sense to simplify that to just:

https://earthmaps.io/boundary/huc/19070506

...which would make things a little easier for the client app.

**Comment by kyleredilla** [comment]
Closed with #109
