### ISSUE TITLE
Clamp precision for returned GeoJSON to 4 or 5 digits of precision

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#121]
4 is probably enough, 5 may be better; the goal is to reduce the amount of floating point noise that we're shipping over the network to reduce the payload size for any requests to the `/boundary/xxx` to get GeoJSON for a polygon.

**Comment by charparr** [comment]
See this function to get started:
https://github.com/ua-snap/data-api/blob/c28482f2dd3914ea1d46bcdb3b3b106deed20580/validate_data.py#L155

This should run on the geojson dict and handle a nested structure.
