### ISSUE TITLE
Some ALFRESCO local endpoints are attempting to assign to a tuple

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/data-api#135]
- http://localhost:5000/alfresco/flammability/local/52.938/-168.868
- http://localhost:5000/alfresco/flammability/local/53.267/-168.217

This code [on line 573 ](https://github.com/ua-snap/data-api/blob/f9130b2f43b19f5c9a8df9fb898ad3396b63158e/routes/alfresco.py#L573) is returning as a tuple in some cases and resulting in this error.

**Comment by Joshdpaul** [comment]
Older ticket, errant line of code is now [306](https://github.com/ua-snap/data-api/blob/b2683d8e71719797a0e2e78503121a05d945e8b4/routes/alfresco.py#L306)
