### ISSUE TITLE
Add HUC12s to boundary endpoint

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#156]
Need to add ability to query `/boundary` endpoint for HUC12 & get GeoJSON back.

Also double-check the inline documentation in the boundary.py route file, it looks outdated where it gives an example.

**Comment by kyleredilla** [comment]
They already are! https://earthmaps.io/boundary/area/190202011303

We can either close or close after adding the proper documentation? Seems to only reference HUC8 on the boundary page.

**Comment by charparr** [comment]
Kyle I'll take a pass through the docs and then close the issue!
