### ISSUE TITLE
ALFRESCO `/local` endpoint fails with 503 code on CSV export

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/data-api#158]
https://earthmaps.io/alfresco/flammability/local/65.4844/-145.4036?format=csv

gives:

"Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:

XID: 165349"

On localhost, fails with "Internal Server Error"

**Comment by BobTorgerson** [comment]
This appears to already be fixed, I'm not getting a backend fetch failure. I just received the CSV correctly from the production API. @kyleredilla Please check this too and close if it works!
