### ISSUE TITLE
4 areas that we may want to remove

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/data-api#169]
These 4 areas return no data for most things and I'm not sure if we want to keep them as available areas from the API:

https://northernclimatereports.org/report/area/FIRE10
https://northernclimatereports.org/report/area/EL25
https://northernclimatereports.org/report/area/NC12
https://northernclimatereports.org/report/area/CD2

**Comment by brucecrevensten** [comment]
Ref https://github.com/ua-snap/iem-webapp/issues/560 

Closing this ticket here, the API behavior is correct and probably we want to address this in the frontend.
