### ISSUE TITLE
USFS3 returning 422 for Veg Type, but not Flam?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#175]
https://earthmaps.io/alfresco/veg_type/area/USFS3

Why is this working for Flam but not veg type?

**Comment by charparr** [comment]
I think that is related to https://github.com/ua-snap/iem-webapp/issues/379#issuecomment-1112544541

The flammability is zero - so there is no vegetation change to model here. In a QGIS sample this is turning up as 'not modeled' aka `0`.
