### ISSUE TITLE
Improve performance of spatial search

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#177]
Right now, it takes a few seconds (~5?) to do the place-based search.  Fine!  But can we do better?  How?

**Comment by charparr** [comment]
Agreed it is kinda slow - and it gets slower each time we add a polygon set. 
We might be able to speed this up by implementing in [pyGEOS](https://pygeos.readthedocs.io/en/stable/index.html) until Shapely 2.0 comes out (see #128 )

**Comment by charparr** [comment]
Getting closer to being able to try addressing with an updated Shapely! [A 2.0 is in pre-release](https://github.com/shapely/shapely/releases/tag/2.0a1). Following.

**Comment by charparr** [comment]
Shapely 2.0 is out, if we set the right backend (either pyGEOS or the alternative) we may get a speedup here. This is if we want to retain this approach and not use the WTH-style database approach.

**Comment by brucecrevensten** [comment]
The faster search is done in Geoserver now, so this ticket can be closed, however there's some work to be done to remove the legacy search code.  Tracked in #270
