### ISSUE TITLE
Update /mmm temperature and precipitation query result examples in documentation (remove model from min/mean/max)

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#187]
The documentation for the `/mmm/temperature` and `/mmm/precipitation` endpoints include the following result examples and structure:

Temperature:
![image](https://user-images.githubusercontent.com/2566292/170366560-af351c3f-ee2d-4ffc-b46c-fa200aaff8eb.png)

Precipitation:
![image](https://user-images.githubusercontent.com/2566292/170366579-5712a133-0afd-423f-b532-4876c8499d20.png)

However, the actual output looks like this (i.e., not nested underneath a model):

Temperature:
```
{
  "historical": {
    "tasmax": 21.7,
    "tasmean": 13.5,
    "tasmin": 6.2
  },
  "projected": {
    "tasmax": 28.5,
    "tasmean": 14.9,
    "tasmin": 1.5
  }
}
```

Precipitation:
```
{
  "historical": {
    "prmax": 23,
    "prmean": 14,
    "prmin": 9
  },
  "projected": {
    "prmax": 23,
    "prmean": 15.6,
    "prmin": 10
  }
}
```

We are omitting the models from the output by design since these numbers are summarized across models, so we just need to update the documentation to reflect this.

**Comment by BobTorgerson** [comment]
Yes, that's true, but those were actually for the /all variety of the end points such as: http://localhost:5000/mmm/temperature/jan/all/64.81/-161.07

**Comment by cstephen** [comment]
Yep, you're right. I was getting confused between the historical/projected/hp vs. all endpoints. This is a non-issue. Closing!
