### ISSUE TITLE
Source data "data layer" and "download link" mismatch in taspr endpoint documentation

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#199]
Looks like a copy & paste typo. The data layer column says temperature, but the link is for precipitation data:

![image](https://user-images.githubusercontent.com/2566292/172703110-33941003-44c2-4a88-b2fc-5b2484295258.png)

**Comment by BobTorgerson** [comment]
This has already been resolved in a previous commit to main.
![fixed](https://github.com/ua-snap/data-api/assets/563260/762df5ea-56cf-4519-ae45-1113c020c998)
