### ISSUE TITLE
Add explainer to home page of API

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#207]
Folks may arrive at the API but really not feel like they can go farther because it's just not explained _what it is_ and _what it's for_.

**Comment by BobTorgerson** [comment]
@brucecrevensten The current version of the API has the following Overview statement: 

> Overview
> This is a data service that facilitates access to a variety of Alaska and Arctic geospatial data.
> 
> The code is hosted on [Github](https://github.com/ua-snap/data-api). Instructions on how to use each data endpoint is given below.

Any suggestions as to what else should be stated to clarify what a person has arrived at?
