### ISSUE TITLE
Consider updating rasterstats to 0.17 for a performance boost

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#209]
The Python package `rasterstats` is used in the API to compute zonal statistics for a polygon, e.g., give me the mean temperature for Denali National Park. A recent [version bump ](https://github.com/perrygeo/python-rasterstats/pull/258) in that package removes a platform type check that was [slowing down some zonal stats computations.](https://github.com/perrygeo/python-rasterstats/issues/256). I'm not certain we'd get a boost but I don't see a downside to trying.

**Comment by charparr** [comment]
Let's bump this package version, may or may not get a small perf boost - but low risk in my opinion.

**Comment by cstephen** [comment]
The rasterstats module was updated to 0.17 in commit 88b0d1b.
