### ISSUE TITLE
Fix hub_bb typo in vectordata.py

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#212]
Here: https://github.com/ua-snap/data-api/blob/10886be3fd545d2feb1bcaddbc48c4bb0a338589/routes/vectordata.py#L60

The variable name should be `huc_bb`, not `hub_bb`. This and any code that uses this variable will need fixed.

**Comment by BobTorgerson** [comment]
This has been dealt with by removing the need to search through the local files in the /places/search endpoint. All of that work is now done on Geoserver, and the functions have changed entirely.
