### ISSUE TITLE
Marine Datasets may need to override the BBOX

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#221]
The current upper bound of `71.3694` might truncate some marine datasets like landfast sea ice. These data may need to override that config or import something else, e.g., `MARINE_BBOX_NORTH` or something like that. We want to avoid an unneeded 422 when there is actually data.

**Comment by Joshdpaul** [comment]
@charparr can this issue be closed? I see a `SEAICE_BBOX` in `config.py` and I am assuming that addresses this issue

**Comment by charparr** [comment]
@Joshdpaul I'd prefer to keep this issue open for now because we are going to need to revisit the landfast seaice dataset and endpoint as that dataset gets developed by Mahoney and others. We'll have a new dataset and a new coverage, and there will be a big overhaul of the endpoint because I'm expecting the underlying data structure to change quite a bit.

Actually - that BBOX current in the code may service the sea ice concentration data instead / as well.
