### ISSUE TITLE
"No data" for previously working historical degree day queries to Apollo

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/data-api#233]
After ingesting new ERA-Interim dergree day coverages that have been truncated to 1980-2009 (see [this issue](https://github.com/ua-snap/rasdaman-ingest/issues/51#issue-1425972545)), we are seeing a"No data" response in the dev API for example queries that should work, e.g.: http://data-api-arctic-eds.eba-hkca5w5b.us-west-2.elasticbeanstalk.com/mmm/degree_days/heating/historical/65.0628/-146.1627

**Comment by charparr** [comment]
Not really in the stream of anything recent, but @kyleredilla I think we can close this one? Likely got fixed with the XREF'd issue and just never got closed. The link to the dev API returns data as I'd expect.

**Comment by kyleredilla** [comment]
Yeah that seems right.
