### ISSUE TITLE
Where'd Freezing Index, Heating Degree Days and Thawing Index result tables go?

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/data-api#235]
It appears that something has happened with the Apollo coverage for degree days that has made the API no longer return valid results. We need to figure out what has changed and resolve it for the Arctic EDS report sections to appear again.

**Comment by kyleredilla** [comment]
@BobTorgerson I'm guessing this is related to #233 and is hopefully fixed with #234

**Comment by BobTorgerson** [comment]
It does appear to be fixed in #234, I'm going to merge the PR and push this up to the development API instance.

**Comment by BobTorgerson** [comment]
With #234 this has been fixed in ArcticEDS.
