### ISSUE TITLE
Add Data Source section to Wet Days Per Year Template

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#236]
It is missing! This should link to the WRF source.

**Comment by cstephen** [comment]
Closed in #290.

The Wet Days Per Year documentation template now includes a "Source data" section that links to this GeoNetwork record:

https://catalog.snap.uaf.edu/geonetwork/srv/eng/catalog.search#/metadata/8b51ce8c-7fd9-4541-9736-990c0a008005 

Also included are direct links to the data directory and links to two separate academic papers (for historical vs. projected).
