### ISSUE TITLE
Add data source to `/mmm` endpoints

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#240]
For example,

https://earthmaps.io/mmm/temperature

What historical/projected dataset is used?  Link to GN

**Comment by cstephen** [comment]
Closed in #290.

Documentation for all `/mmm` endpoints has been either folded into an existing 2nd-level endpoint category page (Temperature and Precipitation) with an existing "Source data" table, or moved into a new 2nd-level page with a new "Source data" table. All `/mmm` endpoints now have links to source data (and academic papers too).
