### ISSUE TITLE
Cull "Forest Type" Endpoint

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#244]
XREF #35 

This endpoint is used in zero apps. I think we should cull it before beginning other API gardening. The data source is not rock solid, and it was one of the very first endpoints we developed so the structure of it (relies on grabbing a big pickle file from `luts`) feels outdated.

- [ ] remove the route file
- [ ] remove the route from the import
- [ ] remove from the index template
- [ ] remove the template 
- [ ] remove `"forest": [65535],` from `validate_data.py`

It is very likely we want to bring forest / vegetation back in some form, but we'll use a different backend dataset and try to follow a more recent pattern of endpoint construction.

**Comment by brucecrevensten** [comment]
Upon release, we need to delete the `AlaskaVegetationWetlandComposite_20180412` layer from Geoserver.  (Safe to delete before, too)
