### ISSUE TITLE
Clarify documentation for mmm endpoints

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#247]
Clarify the documentation of the `mmm/temperature` endpoint specifically, but maybe the other `mmm` endpoints as well.

Specifically, be more clear about this phrase:

> temperature values summarized across all models and scenarios

- What models?
- What scenarios?
- How were min/max calculated? Min/max of annual averages, not individual days, right?

**Comment by charparr** [comment]
I'm going to chime in on this issue and say that I am not fond of having `mmm` as a top-level route. I'd rather have it be `some_variable` and/or `some_variable/all` gets you whatever is on Rasdaman, and then `some_variable/mmm` gets you the summary via WCPS or some other summarizing mechanism.

**Comment by brucecrevensten** [comment]
Since we're removing the `mmm` endpoint we can close this ticket.
