### ISSUE TITLE
Split summary of GIPL permafrost min, mean, and max into sections for each model

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/data-api#261]
All of the models are currently averaged together to generate the min, mean, and max for a given time period, but we want those separated into each model for a given time period.

**Comment by brucecrevensten** [comment]
We may want to move forward with this, or, we may want to back off on implementing mean/min/max for permafrost.  Check with team before finalizing

**Comment by BobTorgerson** [comment]
@charparr Do you have any idea if this is something that we want to move forward with? Is Nancy the right person to ask if this is important to do?

**Comment by charparr** [comment]
@BobTorgerson good question! I think mean-min-maxing chunks of time by model is worth doing.

Here is why:
 - It is thematically consistent with other datasets
 - I'm sure somewhere (EDS?) users will want to see the model variance within a time period (i.e., which model is most variable for GIPL?)
 - We need to summarize time chunks, so we need to min-mean-max the GIPL data in some way no matter what. Individual years will run the gamut of cool/wet/hot/dry which can hide the trends. We saw this in a few of our early WMS sample requests.

**Comment by brucecrevensten** [comment]
This ultimately is probably a question of, "what do we want the updated gipl2 endpoint to look like."  It's valid and we have all the data needed in the coverage, but can summarize/combine it differently in the endpoint.  We want to make the returned data more granular, and this is part of that.

**Comment by brucecrevensten** [comment]
This work was completed as part of integrating the GIPL2 stuff, closing!
