### ISSUE TITLE
Review the `design_index` endpoint

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#293]
Discuss but consider,

 - if we only query `/hp` then remove `/historical` and `/projected` and make a single combined route available
 - should we be summarizing by era, or providing the annual data and offering a `?summarize=era` query parameter?
 -

**Comment by cstephen** [comment]
This issue has been replaced by #321 (delete design indices), and other suggestions are addressed by issues #292 (remove/rename `/mmm` endpoints) and #315 (remove `historical`/`projected` endpoints and always serve both together). Closing this issue.
