### ISSUE TITLE
Sort out (fully) use of Blueprints

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#3]
Blueprints feel like the right way for us to plug in multiple endpoints for the Flask API.  We've got a start of an implementation, but it's likely that "the most Flask-y way" might be different in some ways...

- each major endpoint (blueprint) in its own folder with its own resources
- name of blueprints being used in the prefixing of the handler functions `@simple_page.route('/', defaults={'page': 'index'})` etc

**Comment by brucecrevensten** [comment]
I'm just going to close this; I think we are way, way past when this was relevant.  @charparr @kyleredilla close if you agree, or we can discuss more!

**Comment by kyleredilla** [comment]
Fine with me - I actually never really understood what this meant :D
