### ISSUE TITLE
Scrutinize some older data layers in GeoServer

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#326]
There are some which might have been tied to previous versions of the API but which are now unused / stranded.  Example, `permafrost_beta:magt_cruts31_historical_era1995_1986to2005` + others under the `permafrost_beta` namespace.  Before launch, double-check these and remove any that are clearly unused.

Update the relevant trello card in Q3 AAA board in "launch" column.

**Comment by cstephen** [comment]
I took an inventory and deleted all unused Data API / NCR layers from GeoServer where possible. There are a few other layers we'll be able to delete from GeoServer once we launch the latest Data API progress to production. I've made a note of these layers (mean annual precipitation and forest) in Trello to tackle after launch. Closing this GitHub ticket, though.
