### ISSUE TITLE
Drop the non-dataframe stuff from CSV version of the Permafrost route

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#332]
We don't want the obu/jorgenson stuff in there, omit it.  we don't want to bake heterogenous data structures into a single CSV because it doesn't make sense in terms of a user doing analysis on the data.

**Comment by BobTorgerson** [comment]
I believe we are simply tearing out the entirety of the old permafrost stuff and implementing the GIPL2 instead, so this may be a non-issue once that has been done.

**Comment by charparr** [comment]
We may retain Obu et al + Jorgenson though - these are currently map layers in the dev version of the EDS, so hold on the phone on ripping those out.

**Comment by Joshdpaul** [comment]
@charparr is EDS using the `/permafrost/point/<lat>/<lon>` endpoint? If so, maybe we revise this endpoint into something specifically for EDS, and not include the GIPL data that we now access thru the the `/permafrost/point/gipl/<lat>/<lon>` endpoint. And then drop it from the API documentation.

For example, `/permafrost/point/eds/<lat>/<lon>` would return just the Obu & Jorgenson data, and be invisible from the API documenation. Kind of a hidden menu for EDS? Then if its dropped from EDS during development  for some reason we can just delete that endpoint.

Do we do that anywhere else or is it an API faux-pas? 🤔
