### ISSUE TITLE
Bad ?arg=value requests still give data

### ISSUE THREAD

**Issue by Joshdpaul** [ua-snap/data-api#337]
For example, see the `fetch_mmm_point_data()` function in  `taspr.py`. The script checks for a `?summarize=mmm` argument via `if request.args.get("summarize") == "mmm":` condition. However any typo in this argument (or any argument at all for that matter) will default this condition to return 'None' in which case the script moves to the `else:` condition and continues to execute.

For example, the endpoints below with bad arguments all return data, but should probably return an error instead to avoid confusion:

http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?summarize=max
http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?summarize=mmmm
http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?summary=mmm
http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?foo=bar

Consider using a zero-length argument dictionary check first, eg:

`if len(request.args) == 0:  
     return "default endpoint"`

then check for arguments explicitly, eg: 

`elif: "summarize" in request.args:  
        if request.args.get("summarize") == "mmm":  
                 summarize the data  
        else: throw an error`

**Comment by Joshdpaul** [comment]
This issue was addressed in  #341 but only for the `permafrost.py` route. Consider explicit argument validation: either route-specific (as done in `permafrost.py` or as new API-wide function (see #339 ).

**Comment by brucecrevensten** [comment]
https://marshmallow.readthedocs.io/en/stable/

**Comment by Joshdpaul** [comment]
Affected endpoints:

https://earthmaps.io/degree_days/
https://earthmaps.io/hydrology/
https://earthmaps.io/snow/
https://earthmaps.io/taspr/
