### ISSUE TITLE
Add academic citation to Precip Frequency

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#340]
For the documentation section, this should be added,

```Bieniek P, Walsh J, Fresco N, Tauxe C, Redilla K. Anticipated changes in Alaska extreme precipitation. Journal of Applied Meteorology and Climatology. 2022; 61(2):97-108. https://doi.org/10.1175/JAMC-D-21-0106.1```

**Comment by charparr** [comment]
This Bieniek ref got added somewhere along the way! 
![image](https://github.com/ua-snap/data-api/assets/7774271/e985c16a-25da-4346-9819-3e1b88d0c2fb)
Closing.
