### ISSUE TITLE
Add references / links to hydrology documentation

### ISSUE THREAD

**Issue by Joshdpaul** [ua-snap/data-api#363]
There are two additional references/links that need to be added, once they are ready:

- The paper Jeremy Littell is writing about this data as we are serving it (decadal monthly summaries): we can see if he has a title and add an _(in prep)_ or _(in review)_ or whatever.
- The link to the dataset on on our own GeoNetwork Data Portal once it is live.

**Comment by charparr** [comment]
GeoNetwork Data Portal Link: https://catalog.snap.uaf.edu/geonetwork/srv/eng/catalog.search#/metadata/2610188c-aa38-4f47-8987-b36ec72cdd0d

**Comment by BobTorgerson** [comment]
@brucecrevensten Do we know if Jeremy has a paper for us to put up for him on this page?
