### ISSUE TITLE
Add endpoint for the IEM domain

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/data-api#37]
We probably need the shapefile for the IEM domain in the API somewhere

**Comment by charparr** [comment]
Do we want an endpoint for IEM domain and/or IEM domain + Aleutians?
Could be routes like:
 - `boundary/projectdomain/iem`
 - `boundary/projectdomain/ak`
 - `boundary/projectdomain/iemaleutian`

**Comment by kyleredilla** [comment]
oo I like the `projectdomain` endpoint. Hmm not sure which we want though, @brucecrevensten what do you think? If it doesn't hurt then my thought is maybe both.

**Comment by brucecrevensten** [comment]
This is done/complete elsewhere.
