### ISSUE TITLE
Special characters in Indicators CSV are getting mangled

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#397]
possibly the `mm` char?  (MacOS 11.7.6, Excel 16.77.1)

<img width="105" alt="Screen Shot 2023-10-19 at 9 38 05 AM" src="https://github.com/ua-snap/data-api/assets/525049/a5f7add4-b8e2-44c4-8115-27fdf6b8ed48">

**Comment by cstephen** [comment]
Closed by #402.
