### ISSUE TITLE
Slow results returned in situations where they should be cached

### ISSUE THREAD

**Issue by MikeDelue** [ua-snap/data-api#412]
21 Nov - NCR query for Cantwell took about a minute+. On chrome, on a macbook M2 running Ventura 13.2.1. We assumed it was the local internet.
22 Nov - EDS query for Fairbanks took about as long on the same machine and browser but on home internet which is not typically congested.

**Comment by brucecrevensten** [comment]
Cache had dumped after 4 weeks.  We're bumping it up to 2 years, and cache repopulation is in progress.
