### ISSUE TITLE
CSV File Names Incorrectly Formatted with Underscores and Encoding Issues

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#454]
Our API is generating CSV file names with unwanted leading and trailing underscores, such as `_Precipitation for Utqiaġvik (Barrow).csv_` but there seem to be differences between different platforms and/or browsers.

Example URL: https://earthmaps.io/precipitation/frequency/point/71.2905/-156.789?format=csv&community=AK418

On Charlie-Firefox (MacOS 13.2) the file name is rendered as `_Precipitation for Utqiaġvik (Barrow).csv_` but on Charlie-Safari it is `Future Projections of Precipitation for Utqia%C4%A1vik%20%28Barrow%29.csv` so perhaps there URL encoding issues.
 
Bruce-Firefox on MacOS version 14.3.1 yields no stray underscores but the filename encoding fails like in the prior example.

The expected behavior is that the file name should not have leading or trailing underscores and that the place names should be correctly encoded and displayed across all platforms.

**Comment by MikeDelue** [comment]
Mike can replicate this error in Firefox 129.0/MacOS 13.6.6

**Comment by brucecrevensten** [comment]
https://stackoverflow.com/questions/22477273/firefox-and-chrome-appending-underscore-before-and-after-file-name-while-interne
