### ISSUE TITLE
Replace `is` with `are` to match plural third-person subject plural "instructions"

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#483]
https://github.com/ua-snap/data-api/blob/7f61bbecb52a6d505d4fd37232d5469d35934e87/templates/index.html#L18-L19

Minor grammar thing but I noticed it and cannot unsee it now.

**Comment by SeanAverS** [comment]
Hey, could I take this on?

**Comment by charparr** [comment]
@SeanAverS we'd be delighted if you fix this minor issue.

We don't have strict contributing guidelines at this time, but for this issue my suggestion is that you just:
 -  clone the repository
 -  create a feature branch coming off `main`
  - make your change, and create a PR.
  
  We'll then review it. Thanks! Let us know if you have questions.
