### ISSUE TITLE
500 error with HUC query: http://earthmaps.io/iem/huc/19010107

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/data-api#53]
Not sure if this is because the HUC is outside of the IEM domain at some / all points or what, but.. need to 1) think about this and determine what makes a HUC invalid and 2) handle invalid HUCs. 

This might be a case where the HUC is not really invalid, i.e. where it has some overlap with the domain, but where being on the border causes an issue with the current processing code.

**Comment by charparr** [comment]
@kyleredilla I think we can close this one too? Results appear fine to me.

See https://earthmaps.io/taspr/huc/19010107
and 
https://earthmaps.io/huc/huc8/19010107

**Comment by kyleredilla** [comment]
Yeah looks fine to me! I'm guessing this one was resolved with the refactoring of the zonal summary process in [this commit](https://github.com/ua-snap/data-api/pull/56/commits/84ede8aff7089a36aa3613555fade558c7ef385e)? Because that HUC doesn't exceed the eastern or southern extent of the previous, non-Aleutian IEM domain-based coverage. This all just makes me itch to get #57 done though.

**Comment by charparr** [comment]
I think you're right - the commit you linked handled it by masking the no data values. Closing!
