### ISSUE TITLE
Investigate why historical precipitation values differ substantially between main branch and iem_taspr_2km branch

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#54]
For example, if you look at the historical precipitation values from the main branch:

http://earthmaps.io/iem/point/64.80/-147.70

You'll see this:

```
"1910-2009": {
  "DJF": {
    "CRU-TS31": {
      "CRU_historical": {
        "pr": 47,
        ...
      }
    }
  },
  ...
}
```

Compare this with the historical precipitation data from the `iem_taspr_2km` branch for the same lat/lon point (using the new `taspr` endpoint):

http://localhost:5000/taspr/point/64.80/-147.70

```
{
  "1950_2009": {
    "DJF": {
      "CRU-TS40": {
        "CRU_historical": {
          "pr": {
            "hi_std": 28,
            "lo_std": 5,
            "max": 63,
            "mean": 16,
            "min": 0
          }
        }
      }
    },
    ...
  },
  ...
}
```

The mean precipitation value from the `main` branch is 47mm. The mean precipitation value from the `iem_taspr_2km` branch is 16mm. Is this because of the different time range (1910-2009 vs. 1950-2009) or difference in the underlying dataset (CRU TS 3.1 vs CRU TS 4.0)? Or is there a bug in the calculation?

**Comment by kyleredilla** [comment]
Awesome catch Craig! This was a failure on my part to sum the months of a season before averaging for the precip. Nothing wrong with the API here, but processing code in `iem-taspr-2km` branch of `rasdaman-ingest` repo has been fixed and the live coverage in the production Rasdaman server has been updated.
