### ISSUE TITLE
Data fetch for Unalaska fails

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#60]
http://earthmaps.io/taspr/point/53.8733/-166.533

That's the data fetch location for Unalaska.  Should this work?  We need available locations/etc to be in the same between the front-end GUI and the API.

**Comment by charparr** [comment]
We'll need to drill down on these 500 errors. We should be able to catch the following scenarios:

See #17
See #24
See #31
See #34

1.) A user queries a location **beyond the bounds** of the dataset they are querying.
    - This should get handled on the app side first via "shadow-masking" for click queries, by providing max and min bounds for lat-lon "text box" style queries.
     - The API should also validate the lat-lon for point queries. We have this:
  But it is not tested and known to be infallible.
      - We don't have this for HUC queries. What happens when part of the HUC is beyond the bounds of the dataset (Hello Canada!)
      - What is the desired behavior when we catch a case like this? What if some of the queried data exist, but not all?
   
  2.) A user queries a location **within** the bounds of the dataset they are querying **but there is no data at that location**.
    - Gridded data: if it gets served up by our API, "no data" should be a -9999.0 value or a `np.nan` value or similar. We should be able to catch these by checking if any values in the packaged response dictionary are equivalent.
        - We could:
            - Replace the values with a friendly message.
            - Leave them for the app side to deal with.
            - Drop them entirely,
            - Drop them only if all values in the response are equivalent to no data.

**Comment by charparr** [comment]
Closed by #74
