### ISSUE TITLE
Convert permafrost ALT 0.07 values to nodata values before ingest

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#85]
So far, everything has led us to believe that when the value 0.07 shows up for the ALT value in GIPL permafrost output, this is actually nodata. We should confirm that this is the case, and change these values to -9999 before the ingest.

**Comment by charparr** [comment]
@Craig does this still need to be addressed in pre-processing?

**Comment by cstephen** [comment]
Yep, this still needs addressed. I'm not sure how to address this problem without catching potentially legitimate 0.07 ALT values. Where we have seen this issue, it's usually in the form of a long series of 0.07 values, like in the following URL:

https://earthmaps.io/permafrost/point/59.24/-135.51

So maybe we can safely say that if the 0.07 value repeats 2+ times, we can consider it nodata and change the value to -9999 in pre-processing. Unless there's a better approach!

I also just now noticed a similar situation for an ALT value of 0.16 at the following URL:

https://earthmaps.io/permafrost/point/61.0628/-147.1627

Maybe we can consider any very small repeating ALT value to be a nodata value? Unless there's any other information we can use to make this determination.

**Comment by charparr** [comment]
Interesting! I'll look for repeating values and see what I find. I think that's a good approach. I have all this sort of at the top of my brain so it's a good time to tackle this.

**Comment by charparr** [comment]
I think the approach is identify how many times each model/scenario combination repeats the value of the ALT baseline. If it repeats two or more times, we'll convert the values at those indices to `-9999` which is our no data value for this coverage. Consider this count-of-repeated-baseline-ALT-values figure for RCP 4.5 + CCSM4:

![image](https://user-images.githubusercontent.com/7774271/155791327-dec442e8-1cac-4dd7-9d63-dec2eaaf5257.png)

**Comment by charparr** [comment]
Initial findings are that ALT values of `[0.  , 0.01, 0.07, 0.16, 0.17, 0.19, 0.38]` should be regarded with suspicion.

**Comment by charparr** [comment]
OK I think I have this fixed in pre-processing. When running the API locally, neither `/59.24/-135.51` nor 
`/61.0628/-147.1627` return any `alt` key-value pairs. Coverages are updated on Zeus and Apollo.

**Comment by charparr** [comment]
These changes are now updated in the cached API:

https://earthmaps.io/permafrost/point/59.24/-135.51

https://earthmaps.io/permafrost/point/61.0628/-147.1627

This issue won't correspond to a PR because it is a backend update, but it is tied to https://github.com/ua-snap/rasdaman-ingest/pull/19

@cstephen I think we can close this issue if the JSONs look good to you.

**Comment by cstephen** [comment]
Looks good, @charparr! I'll go ahead and close this ticket. Thanks!

Looks like I have some work to do on the API code. I think we want the alt keys to show up with `null`s instead of being removed entirely, but that's due to the nodata pruning code I added earlier being overly aggressive. I'll make a ticket for that & also to remove the 0.07 detection in the web app code.
